### ISSUE TITLE
Problems interacting strangely with mods such as wooden hopper

### ISSUE THREAD

**Issue by citric-sulfur** [yurisuika/Compost#4] opened 2023-07-04 06:11 UTC
[debug.log](https://github.com/yurisuika/Compost/files/11945057/debug.log)
[latest.log](https://github.com/yurisuika/Compost/files/11945058/latest.log)

![javaw_aI0uytkTgJ](https://github.com/yurisuika/Compost/assets/58549979/ec7bf4d0-0c89-4b27-bf33-9116e97d472c)
It is not composted and is stored.
Destroying the composter in this state does not drop the seeds.

![javaw_TvNkxwO148](https://github.com/yurisuika/Compost/assets/58549979/e7e852be-7fc6-46fc-ab1b-004e82de30a1)
Must use wooden hopper again to eject.

![javaw_XF9aAKlFPF](https://github.com/yurisuika/Compost/assets/58549979/9669b1dc-754d-4aa7-8a2d-52abba7e9d29)
All items will be stored.

![javaw_Du98mykPTX](https://github.com/yurisuika/Compost/assets/58549979/7b4f58c4-47cd-4dd0-a3f4-98e7c2bf5ae2)
![javaw_6GBMDAT7YR](https://github.com/yurisuika/Compost/assets/58549979/490172a9-6f26-4702-94ed-6d702f96b250)
The same problem occurs with similar blocks in different mods.

**Comment by yurisuika** [comment] 2023-07-06 10:33
Ah, okay it didn't occur to me when you said wooden hopper that you were referring to a mod. For some reason the wooden part of the composter and the hopper amalgamated in my mind and it just went through me.

So, on Forge for some reason it is all screwy and I had to disable `insertHook` of Forge's `VanillaInventoryCodeHooks` from running because this was happening with the vanilla hopper. I cannot figure out what exactly goes wrong with it, so just stopping this if statement from returning `true` makes it work with the vanilla hopper. I don't know if it has any side effects, but it was enough to get it going.
![image](https://github.com/yurisuika/Compost/assets/7410303/76b26d50-6d54-4816-8a25-bed6ed2f4631)

Unless I can figure out what can actually be fixed with that, you will have to use a version of the mod prior to `1.2.0` if you want it to work with this mod, This is only a problem with the Forge version, the Fabric one did not need this workaround.

**Comment by yurisuika** [comment] 2024-01-14 04:41
Good news! I finally figured out the issue. It had to use Forge's ItemStackHandler for an inventory. Will probably have the update out tomorrow.

**Closed by yurisuika** 2024-01-14 04:41 UTC

**Comment by yurisuika** [comment] 2024-01-14 23:22
Well it turns out I was wrong, it actually didn't fix it because I was testing the Fabric version on Forge. I was dead tired at the time so you can blame it on that haha. But after a bit more research today I figured out the real issue and have confirmed it to now work! We'll see, I might still be able to get a release out tonight.

**Comment by yurisuika** [comment] 2024-01-15 15:26
The issue was specifically that the blockentity did override the `isValid` method, which is basically the `canInsert` method without the side parameter. It wasn't till I was looking through another mod that uses mojmaps instead of yarn that this realization came to me, as those methods are called `canPlaceItem` and `canPlaceItemThroughFace` there.
