### ISSUE TITLE
[Forge 1.20.1] Fails to load with REI

### ISSUE THREAD

**Issue by vizthex123** [yurisuika/Compost#8] opened 2024-06-09 02:40 UTC
I did report it to them: https://github.com/shedaniel/RoughlyEnoughItems/issues/1653

but figured I'd cross-post it here just in case.

Here's my log:
[latest.log](https://github.com/user-attachments/files/15750351/latest.log)

**Comment by yurisuika** [comment] 2024-06-20 02:19
Duplicate of #7

**Closed by yurisuika** 2024-06-20 02:19 UTC
